### ISSUE TITLE
Start screens

### ISSUE THREAD

**Issue by edoomm** [evaseac/mobile-app#7]
Implement the following screens

![Image](https://user-images.githubusercontent.com/57675992/212872189-a5a797fa-8c59-4ab3-8674-642c2d9b8182.png)

The design could be a little bit difficult, so the implementation should not be 100% alike to the mock up in this first delivery

**Comment by edoomm** [comment]
@EstebanOlmedo [in the Canva](https://www.canva.com/design/DAE7QXO4yLY/pZ6xBHt3cBwu8MxvYCCXnw/edit?utm_content=DAE7QXO4yLY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) you'll find some of the images, feel free to edit the mock ups if you need to.

As for the log in, I lost the image without the components, I only have the full quality image. Maybe you can use some _remove-objects-from-photos_ online editor.

![Image](https://user-images.githubusercontent.com/57675992/214906697-38f41c40-c53b-467a-9a41-2ffec593df17.png)

Or if it helps, here are some photos I found I still have for other sections within the app.


![Image](https://user-images.githubusercontent.com/57675992/214907017-6a612380-17e2-40cd-94e4-5f8a9852fb7d.png)



![Image](https://user-images.githubusercontent.com/57675992/214907023-c1683d83-0498-45a2-9332-4004fefe9870.png)



![Image](https://user-images.githubusercontent.com/57675992/214907041-64670469-dc34-4f1e-93fa-01c81fa8f63d.png)



![Image](https://user-images.githubusercontent.com/57675992/214907051-cc84c6a7-e534-4a74-b7f0-82029a5ea951.png)



![Image](https://user-images.githubusercontent.com/57675992/214907059-7fa50658-0e74-46e1-a73c-992c6a61c807.png)



![Image](https://user-images.githubusercontent.com/57675992/214907062-be8389be-56c8-4426-b27e-da5a13a14bdb.png)

**Comment by edoomm** [comment]
I just created a [page in our notion](https://www.notion.so/edoomm/Design-resources-11ef338173bb4ecd8a8ffc52b758b70a) where all of these images are better organized. Please use it too if you are able to remove the components of the log in screen, so we don't lose these resources.

**Comment by EstebanOlmedo** [comment]
Done in #15
